name: Generate Snake

on:
  schedule:
    - cron: "0 */1 * * *"  # runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: VivekChaudhary111
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            - name: Generate snake animation SVG

      - name: Create output directory
        run: mkdir -p dist

      - name: Move generated files to 'dist' folder
        run: |
          mv github-snake.svg dist/
          mv github-snake-dark.svg dist/ || echo "No dark version generated"


      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
